project_id = "mzcjffaocsbmtjqclzmo"

[functions.create-checkout]
verify_jwt = false

[functions.capture-paypal]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false

[functions.send-return-notification]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.send-subscription-reminders]
verify_jwt = false

[functions.shop-webhook]
verify_jwt = false

[functions.submit-contact-ticket]
verify_jwt = false

[functions.process-return]
verify_jwt = false

[functions.chat]
verify_jwt = false
