project_id = "mzcjffaocsbmtjqclzmo"

[functions.create-checkout]
verify_jwt = false

[functions.capture-paypal]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false

[functions.send-return-notification]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false
